apiVersion: v1
kind: Namespace
metadata:
  name: c2c-test-azure-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-test-azure-deployment
  namespace: c2c-test-azure-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: eslattacr.azurecr.io/azure-demo-push-repo:278679554c3e68abfea864f0553e3f9d82f9a17d

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-test-azure-label
  name: c2c-test-azure-service
  namespace: c2c-test-azure-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---